name: "go-test"
description: "testing for GO"
inputs:
  # Path/s to execute test
  path:
    required: true
  test-report-path:
    required: true
  coverage-report-path:
    required: true
runs:
  using: "composite"
  steps:
    - run: cd ${{ inputs.path }}
      shell: bash
    - run: go test -coverprofile=${{ inputs.coverage-report-path }} -json -v ./... > ${{ inputs.test-report-path }}
      shell: bash
