name: "goreleaser"
description: "Build and release for GO"
inputs:
  args:
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/gorelease.sh "${{ inputs.args }}"
      shell: bash
