name: "go-build"
inputs:
  packages:
    required: true
  output:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        go mod download
        go build -i -o ${{ inputs.output }} ${{ inputs.packages }}
      shell: bash
