name: "go-build"
inputs:
  packages:
    required: true
  output:
    required: true
  artifact-name:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        go mod download
        go build -i -o ${{ inputs.output }} ${{ inputs.packages }}
      shell: bash
    - name: upload build as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.output }}
