name: CI
on:
  pull_request:
    branches: main
    tags:
jobs:
  # TODO: How to copy repository to container?
  lint:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      # local path: ./.github/actions/my-action, public action: {owner}/{repo}/{path}@{ref}
      # Choose the right linting action for your language
      - uses: actions/lint@v1
  test:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      # Choose the right testing action for your language
      - uses: actions/test@v1
  sonarQube:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      - uses: actions/sonar-qube@v1
