name: CI
on: [push, pull_request]
jobs:
  lint:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      # local path: ./.github/actions/my-action, public action: {owner}/{repo}/{path}@{ref}
      # Choose the right linting action for your language
      - uses: actions/checkout@v2
      - uses: ./.github/actions/go-lint
        with:
          path: ./app...
          output: lint.xml # standardized path to match sonarqube properties
          artifact-name: lint-result
          #config-path:
  test:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      # Choose the right testing action for your language
      - uses: actions/checkout@v2
      - uses: ./.github/actions/go-test
        with:
          path: ./test
          test-report-artifact-name: test-report
          test-report-path: tests.out # standardized path to match sonarqube properties
          coverage-report-artifact-name: coverage-report
          coverage-report-path: coverage.out # standardized path to match sonarqube properties
  sonarScan:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      - uses: actions/checkout@v2
      # - uses: docker://sonarsource/sonar-scanner-cli:latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Download test results
        uses: actions/download-artifact@v1
        with:
          name: test-report
          path: tests.out
      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: coverage-report
          path: coverage.out
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
