name: CI
on: [push, pull_request]
jobs:
  # TODO: How to copy repository to container?
  lint:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      # local path: ./.github/actions/my-action, public action: {owner}/{repo}/{path}@{ref}
      # Choose the right linting action for your language
      - uses: actions/checkout@v2
      - uses: actions/lint@v1
  test:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      # Choose the right testing action for your language
      # TODO: How to reference repo's actions
      # TODO: How to specify input for github actions
      - uses: actions/checkout@v2
      - uses: actions/test@v1
  sonarScan:
    container:
      image:
      env:
      ports:
      volumes:
      options:
    steps:
      - uses: actions/checkout@v2
      - uses: docker://sonarsource/sonar-scanner-cli:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
